# Generated by Django 3.2.8 on 2021-11-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
